version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    container_name: lgp-app
    volumes:
      - .:/linear-graph-project
    ports:
      - "8050:8050"  # Adjust if your app uses a different port

#volumes:
  #venv:  # Defines a Docker-managed volume
