version: "3.8"
services:
  lgp-app-dev:
    build:
      context: ..
      dockerfile: ci/Dockerfile.dev
    container_name: lgp-app-dev
    volumes:
      - ../app.py:/app/app.py
    ports:
      - "8050:8050"
    # command: tail -f /dev/null
    entrypoint: ["poetry", "run", "python", "app.py"]
