version: "3.8"
services:
  lgp-app:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    container_name: lgp-app
    ports:
      - "8050:8050"  # Adjust if your app uses a different port
